SET DEFINE OFF;

BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('AUDIT_SECURITY_LOGS', 'CHAIN_OF_CUSTODY_LEDGER', 'CASE_EVIDENCE_FILES', 'CASE_PROFILES', 'INVESTIGATION_UNITS', 'POLICE_DIVISIONS', 'VAULT_SYSTEM_USERS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 1. Jurisdictional Divisions (Cities/Districts)
CREATE TABLE police_divisions (
    division_code VARCHAR2(30) PRIMARY KEY,
    division_name VARCHAR2(150) NOT NULL,
    division_password VARCHAR2(100) NOT NULL,
    nodal_officer_email VARCHAR2(100) NOT NULL
);

-- 2. Police Stations / Units with Station-Level PINs
CREATE TABLE investigation_units (
    unit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_code VARCHAR2(30) REFERENCES police_divisions(division_code) ON DELETE CASCADE,
    unit_name VARCHAR2(100) NOT NULL,
    station_password VARCHAR2(100) NOT NULL,
    area_zone VARCHAR2(100) DEFAULT 'Zone 1 (North)',
    CONSTRAINT unq_div_unit UNIQUE (division_code, unit_name)
);

-- 3. Case Profiles
CREATE TABLE case_profiles (
    case_no VARCHAR2(50) PRIMARY KEY,
    case_name VARCHAR2(150) NOT NULL,
    fir_no VARCHAR2(50) NOT NULL,
    crime_location VARCHAR2(150) NOT NULL,
    case_condition VARCHAR2(50) DEFAULT 'Under Investigation',
    punishment_details VARCHAR2(300) DEFAULT 'Pending Trial / No Conviction Yet',
    conviction_date VARCHAR2(30) DEFAULT 'N/A',
    division_code VARCHAR2(30) REFERENCES police_divisions(division_code) ON DELETE CASCADE,
    area_zone VARCHAR2(100) DEFAULT 'Zone 1 (North)',
    unit_name VARCHAR2(100) NOT NULL,
    registered_by VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Case Evidence Files (AES-256 Encrypted & AI Indexed)
CREATE TABLE case_evidence_files (
    evidence_id VARCHAR2(50) PRIMARY KEY,
    case_no VARCHAR2(50) REFERENCES case_profiles(case_no) ON DELETE CASCADE,
    evidence_title VARCHAR2(200) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    raw_file_name VARCHAR2(255) NOT NULL,
    encrypted_path VARCHAR2(350) NOT NULL,
    sha256_hash VARCHAR2(64) NOT NULL,
    vault_locker VARCHAR2(100) NOT NULL,
    ai_classification VARCHAR2(100) DEFAULT 'Unclassified Exhibit',
    ocr_extracted_text CLOB,
    active_custody_officer VARCHAR2(100) DEFAULT 'VAULT',
    uploaded_by VARCHAR2(100) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    blockchain_tx_hash VARCHAR2(66),
    blockchain_block_number NUMBER,
    blockchain_status VARCHAR2(20) DEFAULT 'PENDING'
);

-- 5. Chain-of-Custody Ledger
CREATE TABLE chain_of_custody_ledger (
    transfer_id NUMBER PRIMARY KEY,
    evidence_id VARCHAR2(50) REFERENCES case_evidence_files(evidence_id) ON DELETE CASCADE,
    case_no VARCHAR2(50) NOT NULL,
    from_officer VARCHAR2(100) NOT NULL,
    to_officer_badge VARCHAR2(50) NOT NULL,
    to_officer_name VARCHAR2(100) NOT NULL,
    to_officer_rank VARCHAR2(50) NOT NULL,
    to_officer_mobile VARCHAR2(15) DEFAULT '9876543210',
    to_officer_email VARCHAR2(100) DEFAULT 'officer@police.gov.in',
    division_code VARCHAR2(30) NOT NULL,
    unit_name VARCHAR2(100) NOT NULL,
    checkout_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    court_return_deadline TIMESTAMP NOT NULL,
    custody_status VARCHAR2(30) DEFAULT 'CHECKED_OUT',
    return_time TIMESTAMP NULL,
    return_condition VARCHAR2(50) DEFAULT 'Pending',
    transfer_reason VARCHAR2(250) DEFAULT 'Official Investigation / Custody Transfer'
);

-- 6. Tamper-Evident Chained Audit Logs
CREATE TABLE audit_security_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prev_log_hash VARCHAR2(64) NOT NULL,
    event_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actor_badge VARCHAR2(100) NOT NULL,
    role VARCHAR2(50) NOT NULL,
    action_type VARCHAR2(100) NOT NULL,
    target_reference VARCHAR2(100) NOT NULL,
    ip_address VARCHAR2(50) NOT NULL,
    log_hash VARCHAR2(64) NOT NULL
);

-- 7. System Users with Identity-Based RBAC
CREATE TABLE vault_system_users (
    badge_id VARCHAR2(50) PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(100) NOT NULL,
    officer_name VARCHAR2(100) NOT NULL,
    officer_email VARCHAR2(100) DEFAULT 'officer@police.gov.in',
    police_rank VARCHAR2(100) DEFAULT 'Sub-Inspector / IO',
    rank_level NUMBER(1) DEFAULT 1,
    role VARCHAR2(30) NOT NULL,
    division_code VARCHAR2(30) DEFAULT 'SURAT',
    area_zone VARCHAR2(100) DEFAULT 'Zone 1 (North)',
    unit_name VARCHAR2(100) DEFAULT 'Katargam Police Station',
    is_active NUMBER(1) DEFAULT 1
);

-- =========================================================
-- SEED DATA (NO CASES, NO MOCK EVIDENCE FILES)
-- =========================================================

-- Cities
INSERT INTO police_divisions VALUES ('SURAT', 'Surat City Police Commissionerate', 'surat123', 'cp.surat@gujarat.gov.in');
INSERT INTO police_divisions VALUES ('AHMEDABAD', 'Ahmedabad City Police Commissionerate', 'ahmedabad123', 'cp.ahmedabad@gujarat.gov.in');
INSERT INTO police_divisions VALUES ('RAJKOT', 'Rajkot City Police Commissionerate', 'rajkot123', 'cp.rajkot@gujarat.gov.in');

-- Stations with Unique PINs
INSERT INTO investigation_units (division_code, unit_name, station_password, area_zone) VALUES ('SURAT', 'Katargam Police Station', 'katar123', 'Zone 1 (North)');
INSERT INTO investigation_units (division_code, unit_name, station_password, area_zone) VALUES ('SURAT', 'Umra Police Station', 'umra123', 'Zone 2 (South)');
INSERT INTO investigation_units (division_code, unit_name, station_password, area_zone) VALUES ('AHMEDABAD', 'Cyber Crime Branch', 'cyber123', 'Cyber Zone');
INSERT INTO investigation_units (division_code, unit_name, station_password, area_zone) VALUES ('RAJKOT', 'Bhaktinagar Police Station', 'bhakti123', 'Zone 1 (East)');

-- System Users with Ranks and Levels
INSERT INTO vault_system_users (badge_id, username, password_hash, officer_name, officer_email, police_rank, rank_level, role, division_code, area_zone, unit_name, is_active)
VALUES ('ADMIN-001', 'admin', 'admin123', 'Inspector General Rajesh Verma', 'dgp.gujarat@police.gov.in', 'Director General of Police (DGP)', 5, 'SUPER_ADMIN', 'SURAT', 'State HQ', 'State Command Center', 1);

INSERT INTO vault_system_users (badge_id, username, password_hash, officer_name, officer_email, police_rank, rank_level, role, division_code, area_zone, unit_name, is_active)
VALUES ('CP-SUR-01', 'cp_surat', 'surat123', 'Shri Anupam Gehlot', 'cp.surat@gujarat.gov.in', 'Commissioner of Police (City CP)', 4, 'COMMISSIONER', 'SURAT', 'City Central', 'Surat Headquarters', 1);

INSERT INTO vault_system_users (badge_id, username, password_hash, officer_name, officer_email, police_rank, rank_level, role, division_code, area_zone, unit_name, is_active)
VALUES ('IO-SUR-102', 'io_surat', 'io123', 'Police Inspector V. Jadeja', 'v.jadeja@suratpolice.gov.in', 'Police Inspector (SHO)', 2, 'INSPECTOR_SHO', 'SURAT', 'Zone 1 (North)', 'Katargam Police Station', 1);

INSERT INTO vault_system_users (badge_id, username, password_hash, officer_name, officer_email, police_rank, rank_level, role, division_code, area_zone, unit_name, is_active)
VALUES ('FSL-SUR-201', 'forensic_lab', 'forensic123', 'Dr. Meera Rao', 'm.rao@fslgujarat.gov.in', 'Forensic Scientist Lead', 1, 'FORENSIC_EXAMINER', 'SURAT', 'Zone 1 (North)', 'Katargam Police Station', 1);

INSERT INTO vault_system_users (badge_id, username, password_hash, officer_name, officer_email, police_rank, rank_level, role, division_code, area_zone, unit_name, is_active)
VALUES ('JUDGE-007', 'judge_portal', 'court123', 'Honorable Sessions Judge A. Dave', 'a.dave@court.gov.in', 'Sessions Judge', 1, 'COURT_JUDICIAL', 'SURAT', 'Judicial District', 'Sessions Court', 1);

-- Genesis Audit Block
INSERT INTO audit_security_logs (prev_log_hash, actor_badge, role, action_type, target_reference, ip_address, log_hash)
VALUES ('0000000000000000000000000000000000000000000000000000000000000000', 'SYSTEM', 'ROOT', 'GENESIS_BLOCK', 'SYSTEM_INITIALIZATION', '127.0.0.1', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');

-- 3. Insert DCP - Surat Zone 1 (Rank Level 3)
INSERT INTO vault_system_users (badge_id, username, password_hash, officer_name, police_rank, rank_level, role, division_code, area_zone, unit_name, officer_email, is_active)
VALUES ('DCP-SUR-01', 'dcp_surat_zone1', 'dcp123', 'Himanshu Verma', 'Deputy Commissioner of Police (DCP)', 3, 'DCP_ACP', 'SURAT', 'Zone 1', 'Zone 1 Headquarters', 'dcp.zone1@suratpolice.gov.in', 1);

COMMIT;

